#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
HISTDUP=erase

export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
# export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go

eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

eval "$(/home/dave/miniconda3/bin/conda shell.zsh hook)" 
