#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
HISTDUP=erase

export MINICONDA=$HOME/miniconda3

export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
# export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
export PATH=$MINICONDA/bin:$PATH

eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$MINICONDA/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$MINICONDA/etc/profile.d/conda.sh" ]; then
        . "$MINICONDA/etc/profile.d/conda.sh"
    else
        export PATH="$MINICONDA/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$MINICONDA/etc/profile.d/mamba.sh" ]; then
    . "$MINICONDA/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<